import { ClerkProvider } from "@clerk/nextjs";
import { Raleway } from "next/font/google";
import Nav from "@/components/nav";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`min-h-screen font-sans ${raleway.variable}`}>
          <Nav />
          {children}
          <Toaster richColors />
          <div>FOOTER</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
