import { ClerkProvider } from "@clerk/nextjs";
import { Inter, Roboto } from "next/font/google";
import "@/styles/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${roboto.variable}`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
